// Generated by @mnemonica/tactica - DO NOT EDIT
// This file provides complete TypeScript interfaces for Mnemonica types

/* eslint-disable @typescript-eslint/no-empty-object-type */
/* eslint-disable @typescript-eslint/no-empty-interface */

import type { ProtoFlat } from 'mnemonica';

export type RequestData = {
	method: string;
	url: string;
	query: Record<string, unknown>;
	params: Record<string, unknown>;
	body: Record<string, unknown>;
	headers: Record<string, unknown>;
	requestId: string;
	RouteData: new (routeInfo: { pagePath: string; isMain: boolean; deep: string }) => RequestData_RouteData;
};

export type RequestData_RouteData = ProtoFlat<RequestData, {
	pagePath: string;
	isMain: boolean;
	deep: string;
	PageData: new (pageFiles: { header: { title: string; template: string; pageIsCode: boolean; keywords: string; description: string; additional: string } | null; content: string; info: Record<string, unknown>; blocks: Array<{ name: string; value: string }>; path: string }) => RequestData_RouteData_PageData;
	RouteData: undefined;
}>;

export type RequestData_RouteData_PageData = ProtoFlat<RequestData_RouteData, {
	header: { header: { title: string; template: string; pageIsCode: boolean; keywords: string; description: string; additional: string } | null; content: string; info: Record<string, unknown>; blocks: Array<{ name: string; value: string }>; path: string }['header'];
	content: string;
	info: Record<string, unknown>;
	blocks: Array<{ name: string; value: string }>;
	path: string;
	RenderData: new (components: Record<string, string | Promise<string>>) => RequestData_RouteData_PageData_RenderData;
	PageData: undefined;
}>;

export type RequestData_RouteData_PageData_RenderData = ProtoFlat<RequestData_RouteData_PageData, {
	components: Record<string, string | Promise<string>>;
	template: string | undefined;
	ResponseData: new (output: { body: string; contentType: string; statusCode: number; fromCache: boolean }) => RequestData_RouteData_PageData_RenderData_ResponseData;
	RenderData: undefined;
}>;

export type RequestData_RouteData_PageData_RenderData_ResponseData = ProtoFlat<RequestData_RouteData_PageData_RenderData, {
	body: string;
	contentType: string;
	statusCode: number;
	fromCache: boolean;
	ResponseData: undefined;
}>;

export type EngineRequest = {
	action: unknown;
	data: unknown;
	leaf: unknown;
	path: unknown;
	template: unknown;
	TreeResult: new (result: { tree: unknown }) => EngineRequest_TreeResult;
	PageResult: new (pageData: unknown) => EngineRequest_PageResult;
	CacheResult: new (cleared: boolean) => EngineRequest_CacheResult;
	TemplateResult: new (templateData: unknown) => EngineRequest_TemplateResult;
};

export type EngineRequest_TreeResult = ProtoFlat<EngineRequest, {
	tree: unknown;
	TreeResult: undefined;
	PageResult: undefined;
	CacheResult: undefined;
	TemplateResult: undefined;
}>;

export type EngineRequest_PageResult = ProtoFlat<EngineRequest, {
	page: unknown;
	PageResult: undefined;
	TreeResult: undefined;
	CacheResult: undefined;
	TemplateResult: undefined;
}>;

export type EngineRequest_CacheResult = ProtoFlat<EngineRequest, {
	cleared: boolean;
	CacheResult: undefined;
	TreeResult: undefined;
	PageResult: undefined;
	TemplateResult: undefined;
}>;

export type EngineRequest_TemplateResult = ProtoFlat<EngineRequest, {
	template: unknown;
	TemplateResult: undefined;
	TreeResult: undefined;
	PageResult: undefined;
	CacheResult: undefined;
}>;
